Update tools

diff --git a/cc-compile b/cc-compile
--- a/cc-compile
+++ b/cc-compile
@@ -1,14 +1,26 @@
 #!/bin/sh
 
+PROGRAM_NAME="cc-compile"
+
+warning()
+{
+  echo "${PROGRAM_NAME}: warn: $1" 1>&2
+}
+
+error()
+{
+  echo "${PROGRAM_NAME}: error: $1" 1>&2
+}
+
 fatal()
 {
-  echo "cc-compile: fatal: $1" 1>&2
+  echo "${PROGRAM_NAME}: fatal: $1" 1>&2
   exit 1
 }
 
 if [ $# -lt 1 ]
 then
-  echo "cc-compile: usage: [@dir] source" 1>&2
+  echo "${PROGRAM_NAME}: usage: [@dir] source" 1>&2
   exit 1
 fi
 
@@ -42,41 +54,51 @@ shift
 
 if [ -f "${BASE_DIR}/conf-x-cc" ]
 then
+  ok=1
+
   CC=`head -n 1 "${BASE_DIR}/conf-x-cc"`
   if [ $? -ne 0 ]
   then
-    fatal "could not read ${BASE_DIR}/conf-x-cc"
+    error "could not read ${BASE_DIR}/conf-x-cc"
+    ok=0
   fi
-  SYSTYPE=`head -n 1 "${BASE_DIR}/conf-x-systype"`
+  SYS_TYPE=`head -n 1 "${BASE_DIR}/conf-x-systype"`
   if [ $? -ne 0 ]
   then
-    fatal "could not read ${BASE_DIR}/conf-x-systype"
+    error "could not read ${BASE_DIR}/conf-x-systype"
+    ok=0
   fi
-  CCTYPE=`head -n 1 "${BASE_DIR}/conf-x-cctype"`
+  CC_TYPE=`head -n 1 "${BASE_DIR}/conf-x-cctype"`
   if [ $? -ne 0 ]
   then
-    fatal "could not read ${BASE_DIR}/conf-x-cctype"
+    error "could not read ${BASE_DIR}/conf-x-cctype"
+    ok=0
   fi
-  CFLAGS="${CFLAGS} `head -n 1 "${BASE_DIR}/conf-x-cflags" 2>/dev/null`"
+  CC_FLAGS="${CC_FLAGS} `head -n 1 "${BASE_DIR}/conf-x-cflags" 2>/dev/null`"
+
+  if [ $ok -eq 0 ]
+  then
+    fatal "could not read required configuration files for cross compilation"
+  fi
 else
   CC=`head -n 1 "${BASE_DIR}/conf-cc"`
   if [ $? -ne 0 ]
   then
     fatal "could not read ${BASE_DIR}/conf-cc"
   fi
-  SYSTYPE=`head -n 1 "${BASE_DIR}/conf-systype"`
+  SYS_TYPE=`head -n 1 "${BASE_DIR}/conf-systype"`
   if [ $? -ne 0 ]
   then
     fatal "could not read ${BASE_DIR}/conf-systype"
   fi
-  CCTYPE=`head -n 1 "${BASE_DIR}/conf-cctype"`
+  CC_TYPE=`head -n 1 "${BASE_DIR}/conf-cctype"`
   if [ $? -ne 0 ]
   then
     fatal "could not read ${BASE_DIR}/conf-cctype"
   fi
 fi
 
-CFLAGS="${CFLAGS} `head -n 1 ${BASE_DIR}/conf-cflags 2>/dev/null`"
+CC_FLAGS="${CC_FLAGS} `head -n 1 ${BASE_DIR}/conf-cflags 2>/dev/null`"
 
 #
 # Read global flag file list, if present.
@@ -87,7 +109,7 @@ then
   for f in `cat "${BASE_DIR}/conf-ccfflist"`
   do
     FLAGS=`cat $f 2>/dev/null`
-    CFLAGS="${CFLAGS} ${FLAGS}"
+    CC_FLAGS="${CC_FLAGS} ${FLAGS}"
   done
 fi
 
@@ -101,7 +123,7 @@ then
   do
     targ="`dirname $out`/`dirname $f`/`basename $f`"
     FLAGS="`cat $targ 2>/dev/null`"
-    CFLAGS="${CFLAGS} ${FLAGS}"
+    CC_FLAGS="${CC_FLAGS} ${FLAGS}"
   done
 fi
 
@@ -109,11 +131,11 @@ fi
 # compensate for any compiler bugs
 #
 
-case ${SYSTYPE} in
+case ${SYS_TYPE} in
   DARWIN)
-    case ${CCTYPE} in
+    case ${CC_TYPE} in
       GCC)
-        CFLAGS="${CFLAGS} -fno-common"  # darwin linker bug workaround
+        CC_FLAGS="${CC_FLAGS} -fno-common"  # darwin linker bug workaround
         ;;
       *)
         ;;
@@ -123,4 +145,4 @@ case ${SYSTYPE} in
     ;;
 esac
 
-exec ${CC} -o ${out}.o -c ${src} ${1+"$@"} ${CFLAGS}
+exec ${CC} -o ${out}.o -c ${src} ${1+"$@"} ${CC_FLAGS}
diff --git a/cc-link b/cc-link
--- a/cc-link
+++ b/cc-link
@@ -1,14 +1,26 @@
 #!/bin/sh
 
+PROGRAM_NAME="cc-link"
+
+warning()
+{
+  echo "${PROGRAM_NAME}: warn: $1" 1>&2
+}
+
+error()
+{
+  echo "${PROGRAM_NAME}: error: $1" 1>&2
+}
+
 fatal()
 {
-  echo "cc-link: fatal: $1" 1>&2
+  echo "${PROGRAM_NAME}: fatal: $1" 1>&2
   exit 1
 }
 
 if [ $# -lt 2 ]
 then
-  echo "cc-link: usage: [@dir] basename objects ..." 1>&2
+  echo "${PROGRAM_NAME}: usage: [@dir] basename objects ..." 1>&2
   exit 1
 fi
 
@@ -31,41 +43,56 @@ fi
 
 if [ -f "${BASE_DIR}/conf-x-ld" ]
 then
+  ok=1
+
   LD=`head -n 1 "${BASE_DIR}/conf-x-ld"`
   if [ $? -ne 0 ]
   then
-    fatal "could not read ${BASE_DIR}/conf-x-ld"
+    error "could not read ${BASE_DIR}/conf-x-ld"
+    ok=0
   fi
-  SYSTYPE=`head -n 1 "${BASE_DIR}/conf-x-systype"`
+  SYS_TYPE=`head -n 1 "${BASE_DIR}/conf-x-systype"`
   if [ $? -ne 0 ]
   then
-    fatal "could not read ${BASE_DIR}/conf-x-systype"
+    error "could not read ${BASE_DIR}/conf-x-systype"
+    ok=0
   fi  
-  LDTYPE=`head -n 1 "${BASE_DIR}/conf-x-ldtype"`
+  LD_TYPE=`head -n 1 "${BASE_DIR}/conf-x-ldtype"`
   if [ $? -ne 0 ]
   then
-    fatal "could not read ${BASE_DIR}/conf-x-ldtype"
+    error "could not read ${BASE_DIR}/conf-x-ldtype"
+    ok=0
   fi
-  LDFLAGS="${LDFLAGS} `head -n 1 ${BASE_DIR}/conf-x-ldflags 2>/dev/null`"
+  LD_FLAGS="${LD_FLAGS} `head -n 1 ${BASE_DIR}/conf-x-ldflags 2>/dev/null`"
+
+  if [ $ok -eq 0 ]
+  then
+    fatal "could not read required configuration files for cross compilation"
+  fi
 else
+  if [ -f "${BASE_DIR}/conf-x-cc" ]
+  then
+    warning "conf-x-cc exists but conf-x-ld does not - native linker used for cross compilation"
+  fi
+
   LD=`head -n 1 "${BASE_DIR}/conf-ld"`
   if [ $? -ne 0 ]
   then
     fatal "could not read ${BASE_DIR}/conf-ld"
   fi
-  SYSTYPE=`head -n 1 "${BASE_DIR}/conf-systype"`
+  SYS_TYPE=`head -n 1 "${BASE_DIR}/conf-systype"`
   if [ $? -ne 0 ]
   then
     fatal "could not read ${BASE_DIR}/conf-systype"
   fi  
-  LDTYPE=`head -n 1 "${BASE_DIR}/conf-ldtype"`
+  LD_TYPE=`head -n 1 "${BASE_DIR}/conf-ldtype"`
   if [ $? -ne 0 ]
   then
     fatal "could not read ${BASE_DIR}/conf-ldtype"
   fi
 fi
 
-LDFLAGS="${LDFLAGS} `head -n 1 ${BASE_DIR}/conf-ldflags 2>/dev/null`"
+LD_FLAGS="${LD_FLAGS} `head -n 1 ${BASE_DIR}/conf-ldflags 2>/dev/null`"
 
 #
 # Read global flag file list, if present.
@@ -76,7 +103,7 @@ then
   for f in `cat "${BASE_DIR}/conf-ldfflist"`
   do
     FLAGS=`cat $f 2>/dev/null`
-    LDFLAGS="${LDFLAGS} ${FLAGS}"
+    LD_FLAGS="${LD_FLAGS} ${FLAGS}"
   done
 fi
 
@@ -93,8 +120,8 @@ then
   do
     targ="`dirname $out`/`dirname $f`/`basename $f`"
     FLAGS="`cat $targ 2>/dev/null`"
-    LDFLAGS="${LDFLAGS} ${FLAGS}"
+    LD_FLAGS="${LD_FLAGS} ${FLAGS}"
   done
 fi
 
-exec ${LD} -o ${out} ${1+"$@"} ${LDFLAGS}
+exec ${LD} -o ${out} ${1+"$@"} ${LD_FLAGS}
diff --git a/cc-slib b/cc-slib
--- a/cc-slib
+++ b/cc-slib
@@ -1,14 +1,26 @@
 #!/bin/sh
 
+PROGRAM_NAME="cc-slib"
+
+warning()
+{
+  echo "${PROGRAM_NAME}: warn: $1" 1>&2
+}
+
+error()
+{
+  echo "${PROGRAM_NAME}: error: $1" 1>&2
+}
+
 fatal()
 {
-  echo "cc-slib: fatal: $1" 1>&2
+  echo "${PROGRAM_NAME}: fatal: $1" 1>&2
   exit 1
 }
 
 if [ $# -lt 2 ]
 then
-  echo "cc-slib: usage: [@dir] basename objects ..." 1>&2
+  echo "${PROGRAM_NAME}: usage: [@dir] basename objects ..." 1>&2
   exit 1
 fi
 
@@ -24,29 +36,70 @@ then
   shift
 fi
 
-SYS_TYPE=`head -n 1 "${BASE_DIR}/conf-systype"`
-if [ $? -ne 0 ]
-then
-  fatal "could not read ${BASE_DIR}/conf-systype"
-fi
+#
+# Assume cross-compilation if cross compilation tools are
+# defined.
+#
 
-AR="ar cr"
-if [ -f "${BASE_DIR}/conf-ar" ]
+if [ -f "${BASE_DIR}/conf-x-ar" ]
 then
-  AR=`head -n 1 "${BASE_DIR}/conf-ar"`
+  ok=1
+
+  AR=`head -n 1 "${BASE_DIR}/conf-x-ar"`
   if [ $? -ne 0 ]
   then
-    fatal "could not read ${BASE_DIR}/conf-ar"
+    error "could not read ${BASE_DIR}/conf-x-ar"
+    ok=0
   fi
-fi
 
-RANLIB="ranlib"
-if [ -f ${BASE_DIR}/conf-ranlib ]
-then
-  RANLIB=`head -n 1 ${BASE_DIR}/conf-ranlib`
+  RANLIB=`head -n 1 "${BASE_DIR}/conf-x-ranlib"`
   if [ $? -ne 0 ]
   then
-    fatal "could not read ${BASE_DIR}/conf-ranlib"
+    error "could not read ${BASE_DIR}/conf-x-ranlib"
+    ok=0
+  fi
+
+  SYS_TYPE=`head -n 1 "${BASE_DIR}/conf-x-systype"`
+  if [ $? -ne 0 ]
+  then
+    error "could not read ${BASE_DIR}/conf-x-systype"
+    ok=0
+  fi
+
+  if [ $ok -eq 0 ]
+  then
+    fatal "could not read required configuration files for cross compilation"
+  fi
+else
+  if [ -f "${BASE_DIR}/conf-x-cc" ]
+  then
+    warning "conf-x-cc exists but conf-x-ar does not - native static archiver used for cross compilation"
+  fi
+
+  AR="ar cr"
+  if [ -f "${BASE_DIR}/conf-ar" ]
+  then
+    AR=`head -n 1 "${BASE_DIR}/conf-ar"`
+    if [ $? -ne 0 ]
+    then
+      fatal "could not read ${BASE_DIR}/conf-ar"
+    fi
+  fi
+
+  RANLIB="ranlib"
+  if [ -f ${BASE_DIR}/conf-ranlib ]
+  then
+    RANLIB=`head -n 1 ${BASE_DIR}/conf-ranlib`
+    if [ $? -ne 0 ]
+    then
+      fatal "could not read ${BASE_DIR}/conf-ranlib"
+    fi
+  fi
+
+  SYS_TYPE=`head -n 1 "${BASE_DIR}/conf-systype"`
+  if [ $? -ne 0 ]
+  then
+    fatal "could not read ${BASE_DIR}/conf-systype"
   fi
 fi
 
@@ -57,14 +110,14 @@ rm -f "${main}".a
 ${AR} "${main}".a ${1+"$@"}
 
 case "${SYS_TYPE}" in
-  SUNOS) ;;
+  SUNOS)          ;;
   SCO_OPENSERVER) ;;
-  UNIXWARE) ;;
-  IRIX) ;;
-  DG_UX) ;;
-  UNIXWARE) ;;
-  CRAY_UNICOS) ;;
-  VMS) ;;
+  UNIXWARE)       ;;
+  IRIX)           ;;
+  DG_UX)          ;;
+  UNIXWARE)       ;;
+  CRAY_UNICOS)    ;;
+  VMS)            ;;
   *)
     ${RANLIB} "$main.a"
     ;;
